# Generated by Django 6.1 on 2026-08-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='first_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='last_name',
            new_name='given_name',
        ),
    ]
