# Generated by Django 6.1 on 2026-09-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_first_name_staffinvitation_family_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffinvitation',
            table='staff_invitation',
        ),
    ]
