# Generated by Django 6.1 on 2026-09-16 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'settings_bed_type',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'settings_room_amenity',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=0)),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('room_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='room_type.roomamenity')),
            ],
            options={
                'db_table': 'settings_room_type',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeBed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_beds', models.PositiveIntegerField(default=1)),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type_beds', to='room_type.bedtype')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_beds', to='room_type.roomtype')),
            ],
            options={
                'db_table': 'settings_room_type_bed',
                'unique_together': {('room_type', 'bed_type')},
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_types',
            field=models.ManyToManyField(related_name='room_types', through='room_type.RoomTypeBed', to='room_type.bedtype'),
        ),
    ]
