# Generated by Django 6.1 on 2026-09-22 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('staff', '0003_alter_staffinvitation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('status', 'Booking Status'), ('payment_status', 'Payment Status')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to='staff.staff')),
            ],
            options={
                'db_table': 'booking_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
