# Generated by Django 6.1 on 2026-08-27 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, null=True)),
                ('status', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'branch',
                'ordering': ['sequence'],
            },
        ),
    ]
